name: CI/CD with Self-Hosted Runner

on:
  push:
    branches:
      - main # Or your branch name

jobs:
  deploy:
    runs-on: self-hosted # This specifies the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Deploy the application
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          APP_URL: ${{ secrets.APP_URL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          git pull origin main
          npm install
          pm2 reload ecosystem.config.js --update-env
        shell: bash
