name: CI/CD with Self-Hosted Runner

on:
  push:
    branches:
      - main  # Or your branch name

jobs:
  deploy:
    runs-on: self-hosted  # This specifies the self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Stop running app
      run: |
        node-windows stop backend_main || true
      shell: bash

    - name: Deploy the application
      run: |
        git pull origin main
        npm install
        node-windows stop backend_main || true
        node-windows start backend_main
      shell: bash
