name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install --ignore-engines  # or any other dependency manager

      - name: Set up environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DBNAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DBUSER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DBPASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DBPORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> $GITHUB_ENV
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> $GITHUB_ENV

      - name: Verify environment variables
        shell: pwsh
        run: |
          $missingVars = @()

          if (-not $env:DB_HOST) { $missingVars += "DB_HOST" }
          if (-not $env:DBNAME) { $missingVars += "DBNAME" }
          if (-not $env:DBUSER) { $missingVars += "DBUSER" }
          if (-not $env:DBPASSWORD) { $missingVars += "DBPASSWORD" }
          if (-not $env:DBPORT) { $missingVars += "DBPORT" }
          if (-not $env:EMAIL_USER) { $missingVars += "EMAIL_USER" }
          if (-not $env:EMAIL_PASS) { $missingVars += "EMAIL_PASS" }

          if ($missingVars.Count -gt 0) {
            Write-Error "Missing environment variables: $($missingVars -join ', ')"
            exit 1
          } else {
            Write-Host "All environment variables are set."
          }

      - name: Run Code
        run: |
          npx ts-node src/index.ts  # or any test command
