name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install --ignore-engines  # or any other dependency manager

      - name: Set up environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DBNAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DBUSER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DBPASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DBPORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> $GITHUB_ENV
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> $GITHUB_ENV

      - name: Verify environment variables
        run: |
          # Check for the required environment variables and fail if any are missing
          if [ -z "$DB_HOST" ] || [ -z "$DBNAME" ] || [ -z "$DBUSER" ] || [ -z "$DBPASSWORD" ] || [ -z "$DBPORT" ] || [ -z "$EMAIL_USER" ] || [ -z "$EMAIL_PASS" ]; then
            echo "Error: One or more environment variables are missing"
            exit 1
          else
            echo "All environment variables are set."
          fi

      - name: Run Code
        run: |
          npx ts-node src/index.ts  # or any test command
