name: DEV CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --ignore-engines

      - name: Run Node.js Application
        shell: powershell
        run: |
          # Start the Node.js process and redirect output to a log file
          $process = Start-Process -File "npx" -ArgumentList "ts-node src/index.ts" -RedirectStandardOutput "output.log" -RedirectStandardError "error.log" -PassThru
          Start-Sleep -Seconds 10  # Wait for the server to start

          if (-not $process.HasExited) {
            Write-Host "Node.js application is running. PID: $($process.Id)"
          } else {
            Write-Error "Failed to start the Node.js application."
            exit 1
          }

      - name: Wait for the Node.js app to start
        run: |
          Start-Sleep -Seconds 5  # Additional wait
          
      - name: Health Check
        run: |
          $url = "http://localhost:3000" # Replace with your application URL and port
          $response = Invoke-WebRequest -Uri $url -UseBasicP
          if ($response.StatusCode -ne 200) {
            Write-Error "Health check failed: HTTP status $($response.StatusCode)"
            exit 1
          } else {
            Write-Host "Application is accessible at $url"
          }

      - name: Read Application Logs
        run: |
          echo "Output Log:"
          Get-Content output.log
          echo "Error Log:"
          Get-Content error.log
